# -*- coding: utf-8 -*-
"""txt_web_mining.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14ilo7tkRIrFrcNZww2YwzeJBPM0u2EJZ
"""
import csv
import re

# from google.colab import drive
# drive.mount('/content/drive')

# path = '/content/drive/MyDrive/top-passages-york07ga1.txt'
path = 'top-passages-york07ga1.txt'
with open(path, 'r') as file:
    lines = file.read()
    topics = lines.split('\n\n')
    pattern = r'(\d+)_(\d+)_(\d+\.\d+?)_(\d+)_(\d+)'
    data_list = []
    topic_code = 200
    for topic in topics:
        if topic.startswith(f'Topic: {topic_code}'):
            text = topic.split('\n')[-1].replace(' 2. ', '')
            print(text)
            match = re.findall(pattern, topic)
            match = match[0]
            data_list.append([topic_code, match[0], match[1], match[2], match[3], match[4], text])
            print(f'{topic_code}, {match[0]},{match[1]},{match[2]},{match[3]},{match[4]}, {text}')
    filename = "data.csv"
    with open(filename, 'w', newline='') as csv_file:
        writer = csv.writer(csv_file)
        for row in data_list:
            writer.writerow(row)



